language: rust
rust:
  - stable
#  - beta
#  - nightly

before_script:
  - rustup component add clippy
  - cargo install --force cbindgen
  
env:
  - CARGO_FLAG=clippy --all-targets --all-features -- -D warnings
  - CARGO_FLAG=test
  - CARGO_FLAG=test -- --ignored
  - CARGO_FLAG=test --release
  - CARGO_FLAG=test --release -- --ignored
script:

  - travis_wait 360 cargo $CARGO_FLAG
  # make will build the library, compile the C wrapper
  # and run a simple test on the wrapper
  - make
