language: rust
rust:
  - stable
#  - beta
#  - nightly

before_script:
  - rustup component add clippy
  ########################################################
  # the following block of scripts keeps the travis alive
  # to break the 10 min limitation
  - docker build -t buildroot . > build.log 2>&1
  - while sleep 5m; do echo "=====[ $SECONDS seconds, buildroot still building... ]====="; done &
  - time docker run --rm -v $PWD/build:/build buildroot >> build.log 2>&1
  # Killing background sleep loop
  - kill %1
  ########################################################
env:
  - CARGO_FLAG=clippy --all-targets --all-features -- -D warnings
  - CARGO_FLAG=test
  - CARGO_FLAG=test -- --ignored
  - CARGO_FLAG=test --release
  - CARGO_FLAG=test --release -- --ignored
  - CARGO_FLAG=bench
script:

  - cargo $CARGO_FLAG
