language: rust
rust:
  - stable
#  - beta
#  - nightly

before_script:
  - rustup component add clippy

env:
  - CARGO_FLAG=clippy --all-targets --all-features -- -D warnings
  - CARGO_FLAG=test -- --nocapture
  - CARGO_FLAG=test -- --ignored -- --nocapture
  - CARGO_FLAG=test --release -- --nocapture
  - CARGO_FLAG=test --release -- --ignored -- --nocapture
  - CARGO_FLAG=bench
script:

  - cargo $CARGO_FLAG
