language: rust
rust:
  - stable
  - beta
  - nightly
before_script:
  - rustup component add clippy
script:
  - cargo clippy
  # if you want the build job to fail when encountering warnings, use
  - cargo clippy -- -D warnings
  # in order to also check tests and non-default crate features, use
  - cargo clippy --all-targets --all-features -- -D warnings
  # all sorts of tests with different compiling flags
  - cargo test
  - cargo test -- --ignored
  - cargo test --features=pk_in_g2
  - cargo test --features=pk_in_g2 -- --ignored
  - cargo test --features=pk_in_g2,use_rand_generators
  - cargo test --features=pk_in_g2,use_rand_generators -- --ignored
  - cargo test --release
  - cargo test --release -- --ignored
  - cargo test --features=pk_in_g2 --release
  - cargo test --features=pk_in_g2 --release -- --ignored
  - cargo test --features=pk_in_g2,use_rand_generators --release
  - cargo test --features=pk_in_g2,use_rand_generators --release -- --ignored

if: rust == stable
  - cargo bench

  # etc.
