language: rust
rust:
  - stable
#  - beta
#  - nightly

before_script:
  - rustup component add clippy
  - cargo install --force cbindgen

script:
  - cargo clippy --all-targets --all-features -- -D warnings
  - travis_wait 360 cargo test
  - travis_wait 360 cargo test -- --ignored
  - travis_wait 360 cargo test --release
  - travis_wait 360 cargo test --release -- --ignored

  # make will build the library, compile the C wrapper
  # and run a simple test on the wrapper
  - make
