language: rust
rust:
  - stable
#  - beta
#  - nightly

before_script:
  - rustup component add clippy

env:
  - CARGO_FLAG=clippy --all-targets --all-features -- -D warnings
  - CARGO_FLAG=test
  - CARGO_FLAG=test -- --ignored
  - CARGO_FLAG=test --release
  - CARGO_FLAG=test --release -- --ignored
  - CARGO_FLAG=bench
script:

  - travis_wait 60 cargo $CARGO_FLAG
