[package]
name = "pixel"

version = "0.1.0"
authors = [
    "Zhenfei Zhang <zhenfei@algorand.com>",
]
license = "MIT/Apache-2.0"

description = "Pixel: Algorand's consensus signature over curve BLS12-381"

#[lib]
#crate-type = ["staticlib"]


[dependencies]
rand = "0.4"
#pairing = "0.14"
pairing = {git = "https://github.com/zkcrypto/pairing"}
sha2 = "0.8"
ff = { version = "0.4", features = ["derive"] }
bigint = { version = "4", default-features = false }

[features]
# this flag indicates that the public key lies in group G1 by default
# if we choose to set public key in G1 (a.k.a, switch the groups)
# use `cargo build --features = pk_in_g2`
pk_in_g2 = []

# this flag indicates that we want to use randomized group generators
# as opposite to default group generators
# to enable, use `cargo build --features = use_rand_generators`
use_rand_generators = []
