[package]
name = "pixel"

version = "0.1.0"
authors = [
    "Zhenfei Zhang <zhenfei@algorand.com>",
]
license = "MIT/Apache-2.0"

description = "Pixel: Algorand's consensus signature over curve BLS12-381"

#[lib]
#crate-type = ["staticlib"]


[dependencies]
rand = "0.4"
#pairing = "0.14"
#pairing = {git = "https://github.com/zkcrypto/pairing"}
pairing = { version = "0.14.3", git = "https://github.com/kwantam/pairing", features = [ "transmutable" ] }

sha2 = "0.8"
ff = { version = "0.4", features = ["derive"] }
bigint = { version = "4", default-features = false }
bls_sigs_ref-rs = {git= "https://github.com/kwantam/bls_sigs_ref"}

[features]
# this flag indicates that the public key lies in group G1 by default
# if we choose to set public key in G1 (a.k.a, switch the groups)
# use `cargo build --features = pk_in_g2`
pk_in_g2 = []

# this flag indicates that we want to use randomized group generators
# as opposite to default group generators
# to enable, use `cargo build --features = use_rand_generators`
use_rand_generators = []

# enable this flag will generate more output during debugging
verbose = []

# enable this flag will use deterministic randomness during sk updating
# to enable, use `cargo build --features = use_det_rand`
# currently the deterministic randomness is set by default
# no-det is not supported
# use_det_rand = []
