[package]
name = "pixel"

version = "0.1.0"
authors = [
    "Zhenfei Zhang <zhenfei@algorand.com>",
]
license = "MIT/Apache-2.0"

description = "Algorand's consensus signature over curve BLS12-381"

#[lib]
#crate-type = ["staticlib"]


[dependencies]
rand = "0.4"
#pairing = "0.14"
pairing = {git = "https://github.com/zkcrypto/pairing"}
sha2 = "0.8"
ff = { version = "0.4", features = ["derive"] }
bigint = { version = "4", default-features = false }

[features]
unstable-features = ["expose-arith"]
expose-arith = []
default = []
